name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
    run: |
      echo RP_PASSWORD=${{ secrets.RP_PASSWORD }} >> $GITHUB_ENV
      echo BASIC_AUTH_TOKEN=${{ secrets.BASIC_AUTH_TOKEN }} >> $GITHUB_ENV

    # Login to Docker
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    # Start services using Docker Compose
    - name: Start services
      run: |
        docker-compose -f ./docker-compose.yml up -d

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    # Stop services
    - name: Stop services
      run: |
        docker-compose -f ./docker-compose.yml down

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
